package biz.princeps.landlord;

import biz.princeps.landlord.api.IFlagRegistry;
import com.sk89q.worldguard.protection.flags.Flag;
import com.sk89q.worldguard.protection.flags.Flags;

public enum FlagRegistry implements IFlagRegistry {
/*
    PASSTHROUGH(Flags.PASSTHROUGH),
    BUILD (Flags.BUILD),
    BLOCK_BREAK (Flags.BLOCK_BREAK),
    BLOCK_PLACE (Flags.BLOCK_PLACE),
    USE (Flags.USE),
    INTERACT (Flags.INTERACT),
    DAMAGE_ANIMALS (Flags.DAMAGE_ANIMALS),
    PVP (Flags.PVP),
    SLEEP (Flags.),
    TNT (Flags.),
    CHEST_ACCESS (Flags.),
    PLACE_VEHICLE (Flags.),
    DESTROY_VEHICLE (Flags.),
    LIGHTER (Flags.),
    RIDE (Flags.),
    POTION_SPLASH (Flags.),
    ITEM_PICKUP(Flags.),
    ITEM_DROP (Flags.),
    EXP_DROPS (Flags.),
    MOB_DAMAGE (Flags.),
    MOB_SPAWNING(Flags.),
    CREEPER_EXPLOSION (Flags.),
    ENDERDRAGON_BLOCK_DAMAGE (Flags.),
    GHAST_FIREBALL (Flags.),
    FIREWORK_DAMAGE (Flags.),
    OTHER_EXPLOSION (Flags.),
    WITHER_DAMAGE (Flags.),
    FIRE_SPREAD(Flags.),
    LAVA_FIRE (Flags.),
    LIGHTNING (Flags.),
    WATER_FLOW (Flags.),
    LAVA_FLOW (Flags.),
    PISTONS (Flags.),
    SNOW_FALL (Flags.),
    SNOW_MELT (Flags.),
    ICE_FORM (Flags.),
    ICE_MELT (Flags.),
    MUSHROOMS (Flags.),
    LEAF_DECAY (Flags.),
    GRASS_SPREAD (Flags.),
    MYCELIUM_SPREAD (Flags.),
    VINE_GROWTH (Flags.),
    SOIL_DRY (Flags.),
    ENDER_BUILD (Flags.),
    INVINCIBILITY(Flags.),
    SEND_CHAT(Flags.),
    RECEIVE_CHAT(Flags.),
    ENTRY(Flags.),
    EXIT(Flags.),
    ENDERPEARL(Flags.),
    CHORUS_TELEPORT(Flags.),
    ENTITY_PAINTING_DESTROY(Flags.),
    ENTITY_ITEM_FRAME_DESTROY(Flags.),
    FALL_DAMAGE(Flags.),
     DENY_MESSAGE (Flags.),
     ENTRY_DENY_MESSAGE(Flags.),
     EXIT_DENY_MESSAGE(Flags.),
    EXIT_OVERRIDE(Flags.),
    EXIT_VIA_TELEPORT(Flags.),
     GREET_MESSAGE(Flags.),
     FAREWELL_MESSAGE(Flags.),
     NOTIFY_ENTER(Flags.),
     NOTIFY_LEAVE(Flags.),
    DENY_SPAWN(Flags.),
      GAME_MODE(Flags.),
    TIME_LOCK(Flags.),
    WEATHER_LOCK(Flags.),
     HEAL_DELAY(Flags.),
     HEAL_AMOUNT(Flags.),
     MIN_HEAL(Flags.),
    MAX_HEAL(Flags.),
    FEED_DELAY(Flags.),
     FEED_AMOUNT(Flags.),
     MIN_FOOD(Flags.),
     MAX_FOOD(Flags.),
    TELE_LOC(Flags.),
     SPAWN_LOC(Flags.),
     BLOCKED_CMDS(Flags.),
     ALLOWED_CMDS(Flags.),

    ;

    FlagRegistry(Flag<?> wgflag) {
        Flags.
    }
    */
}
